"""Generate the reviewed lilToon 2.3.4 property allowlist and support table.

Usage: python Tools~/generate_catalog.py <lilToon package directory>
No shader code is copied; only shader/property identifiers and type metadata.
"""
from pathlib import Path
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
package = Path(sys.argv[1])
version = json.loads((package / "package.json").read_text(encoding="utf-8"))["version"]
if version != "2.3.4":
    raise SystemExit("Review classification before generating for another lilToon version.")

properties = {}
shaders = set()
for path in sorted((package / "Shader").glob("*.shader")):
    source = path.read_text(encoding="utf-8-sig")
    shader = re.search(r'^Shader\s+"([^"]+)"', source)
    if not shader or "lilToon" not in shader.group(1):
        continue
    shaders.add(shader.group(1))
    body = source.split("SubShader", 1)[0]
    for line in body.splitlines():
        match = re.search(r'\b(_\w+)\s*\(\s*"[^"]*"\s*,\s*(\w+)', line)
        if not match:
            continue
        name, kind = match.groups()
        row = properties.setdefault(name, {"types": set(), "hidden": False})
        row["types"].add(kind)
        row["hidden"] |= "HideInInspector" in line


def block(name):
    n = name.lower()
    if n.startswith(("_eg", "_e2g")):
        return "発光"
    if n in {"_dummyproperty", "_basemap", "_basecolormap", "_basecolor", "_liltoonversion"}:
        return "内部・派生値"
    if n.startswith("_pre"):
        return "透過・描画設定"
    if any(x in n for x in ("srcblend", "dstblend", "blendop", "stencil", "zwrite", "ztest", "zclip", "offsetfactor", "offsetunits", "colormask", "alphatomask")) or n in {"_cull", "_outlinecull", "_furcull", "_transparentmode", "_asoverlay", "_useclippingcanceller", "_cutoff", "_subpasscutoff", "_alphaboostfa", "_invisible"}:
        return "透過・描画設定"
    if "outline" in n:
        return "輪郭線"
    if "rimshade" in n or "shadow" in n or n == "_ramp":
        return "影"
    if "anisotropy" in n:
        return "異方性反射"
    if "matcap" in n:
        return "MatCap"
    if "rim" in n:
        return "リムライト"
    if "emission" in n:
        return "発光"
    if "bump" in n:
        return "ノーマル"
    if any(x in n for x in ("reflection", "reflectance", "metallic", "smoothness", "specular", "gsaa")):
        return "反射"
    if "backlight" in n or "light" in n or n in {"_asunlit", "_beforeexposurelimit", "_aastrength", "_flipnormal", "_backfaceforceshadow", "_backfacecolor"}:
        return "ライティング"
    for fragment, label in (("alphamask", "アルファマスク"), ("dither", "ディザ"), ("glitter", "ラメ"), ("parallax", "視差"), ("pom", "視差"), ("distancefade", "距離フェード"), ("audiolink", "AudioLink"), ("refraction", "屈折"), ("gem", "宝石"), ("fur", "ファー"), ("tess", "テッセレーション"), ("idmask", "IDマスク"), ("udim", "UDIM破棄")):
        if fragment in n:
            return label
    if "main2" in n or n == "_color2nd":
        return "基本色 2nd"
    if "main3" in n or n == "_color3rd":
        return "基本色 3rd"
    if "dissolve" in n:
        return "ディゾルブ"
    if "main" in n or n in {"_color", "_shiftbackfaceuv"}:
        return "基本色"
    return "その他"


def exclusion(name, row):
    if name in {"_TransparentMode", "_UseOutline", "_UseClippingCanceller", "_AsOverlay"}:
        return "シェーダー・描画モードの変更が必要な設定は対象外"
    if name in {"_BaseColor", "_BaseMap", "_BaseColorMap"}:
        return "派生値: 採用した基本色／MainTexから必要時だけ再計算"
    if row["hidden"]:
        return "内部管理値（グラデーション編集情報・バージョン等）は対象外"
    if name == "_DummyProperty":
        return "シェーダー診断用のダミー値"
    return ""


def cs(value):
    return json.dumps(value, ensure_ascii=False)


lines = ["// Generated by Tools~/generate_catalog.py from lilToon 2.3.4 metadata.",
         "using System.Collections.Generic;", "", "namespace DennokoWorks.MatSync", "{",
         "    internal static class PropertyCatalog", "    {",
         "        internal static readonly HashSet<string> ShaderNames = new HashSet<string>", "        {"]
lines += ["            " + cs(name) + "," for name in sorted(shaders)]
lines += ["        };", "        private static readonly Dictionary<string, string> Blocks = new Dictionary<string, string>", "        {"]
lines += [f"            {{ {cs(name)}, {cs(block(name))} }}," for name in sorted(properties)]
lines += ["        };", "        private static readonly Dictionary<string, string> Exclusions = new Dictionary<string, string>", "        {"]
lines += [f"            {{ {cs(name)}, {cs(exclusion(name, row))} }}," for name, row in sorted(properties.items()) if exclusion(name, row)]
lines += ["        };",
          '        internal static string BlockFor(string name) => Blocks.TryGetValue(name, out var block) ? block : "その他";',
          '        internal static string ExclusionFor(string name) => !Blocks.ContainsKey(name) ? "lilToon 2.3.4対応表にない項目" :',
          "            Exclusions.TryGetValue(name, out var reason) ? reason : null;", "    }", "}"]
(ROOT / "Editor/PropertyCatalog.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")

doc = ["# lilToon 2.3.4 プロパティー対応表", "",
       "同梱環境の標準Shaderディレクトリから抽出した内部名を許可リストとして使用する。未知の内部名は除外する。",
       "各転送時に実際のShaderの型・テクスチャ次元・プロパティーの存在を確認する。FloatとRangeの相互転送を許可し、Intとは区別する。",
       "テクスチャは既定で参照・Tiling・Offsetを保持する。ONの場合だけ転送する。",
       "描画設定は同一シェーダー間のみ対応し、Shader、Render Queue、Override Tagsは転送しない。",
       "通常バリアントはlilToonのRemoveShaderKeywords、MultiはSetupMultiMaterialで採用値から派生状態を整合させる。",
       "非表示のグラデーション編集情報は転送しない。生成済みグラデーションテクスチャはテクスチャONで転送できるが、編集キーは適用先のままとなる。",
       "", "## プロパティー", "", "| 内部名 | 宣言型 | ブロック | 方針 |", "| --- | --- | --- | --- |"]
for name, row in sorted(properties.items()):
    policy = exclusion(name, row) or ("オプションONで転送" if any(t in row["types"] for t in ["2D", "3D", "Cube", "2DArray", "CubeArray"]) else "転送")
    doc.append(f'| `{name}` | {", ".join(sorted(row["types"]))} | {block(name)} | {policy} |')
doc += ["", "## シェーダー許可リスト", "", "内部名と型が共通のプロパティーを処理する。実際の描画とバリアントごとの差異はUnity上で確認する。", ""]
doc += ["- `" + name + "`" for name in sorted(shaders)]
(ROOT / "Docs/Impl/property-support.md").write_text("\n".join(doc) + "\n", encoding="utf-8")
print(f"Generated {len(properties)} properties / {len(shaders)} shaders for lilToon {version}.")
print("Other:", ", ".join(n for n in properties if block(n) == "その他"))
